### ISSUE TITLE
Encounter Segmentation Fault when using external circuit file

### ISSUE THREAD

**Issue by marvellous987** [emp-toolkit/emp-ag2pc#27]
Hi, thanks for the amazing implementation.

I encountered an issue when I try to use an external circuit file, it returns:
```
connected
Segmentation fault: 11
```
for both parties' terminals.

I got the file from https://homes.esat.kuleuven.be/~nsmart/MPC/adder_64bit.txt and saved it in emp-tool/circuit/files/bristol_format

Is there any operations required if we use some external circuit files?

Thank you!

**Comment by wangxiao1254** [comment]
Please use absolute path for the file. I think the code didn't find the circuit file. You can put the circuit file anywhere.

**Comment by marvellous987** [comment]
Thank you for the reply. It works for the absolute path. May I ask if there any ways to accepts a relative path like I put the circuit in emp-tool/circuit/files/bristol_format?

**Comment by wangxiao1254** [comment]
you just use the relative path that it should work, but don't use the append prefix as in the example code, that will direct to somewhere else. Sometime it can be confusing where is your project home. You can always write a dummy file to figure out what is that to know. Anyway I think the rest of the problem is more of C++ than EMP.

**Comment by marvellous987** [comment]
Got it. Thank you very much!
